#Application properties
server:
  port: 8081


#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: key
      secretKey: secret

application:
  bucket:
    name: poc-demo-it05

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
