const chart2data = [
  {
    "rpaValueScore": "TBD",
    "projectManager": "Loic Hascher",
    "affectedQCDimensions": "",
    "capital": 17443912,
    "functionalOwnership": "Pharm - Quality Systems",
    "involvedTechnologyOrSystem": "on",
    "totalProjectValue": 21700000,
    "endDate": "9/14/25",
    "description": "Work to create a common and simple user experience, that is agnostic to underlying source systems and enables automation and compliance to reduce manual work, improve usability/efficiency and eliminate the gaps in user access management. ",
    "roi": "",
    "bamAllignment": "100% Digital QMS",
    "businessObjectivesOrExpectations": "Next Gen QS will be transformational to the way we do business.  It will deliver time savings as processes will be more efficient and the system will be intuitive requiring less training.  It will allow for us to shift resources from repetitive data entry tasks which will be automated by the system to serving as Quality improvement professionals.  Additionally it will provide lower operational costs as the system will be SAAS. \t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n",
    "resourceRequired": "TBD",
    "initiative": "Next Gen Quality Systems",
    "carStatus": "",
    "strategies": [
      "Skillset",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Rob Famiglietti",
    "potentialRisksOrRoadblocks": "-",
    "expense": 7677600,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP21 - Next Gen Quality Systems",
    "projectId": "JSC-0100010",
    "startDate": "9/30/21",
    "primary": "Internal Quality Support",
    "totalProjectCost": 25121512
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Laurens Oort",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Quality PPM",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "9/14/27",
    "description": "CxE will proactively deliver innovative product Quality solutions to enhance customer, consumer experiences and patient outcomes.​",
    "roi": "",
    "bamAllignment": "98% Satisfaction in Customer Facing KPIs",
    "businessObjectivesOrExpectations": "Pharma prioritization includes reduce ​one-press user errors, reduce damaged needle, reduce Tremfya Plunger Separations, reduce Tremfya & Stelara UltraSafe user errors, reduce Product Dose Omission (Missed Dose)​, reduce Tremfya & Stelara UltraSafe user Errors​, and ​reduce Lack of Effect (LOE).",
    "resourceRequired": "TBD",
    "initiative": "-",
    "carStatus": "",
    "strategies": [
      "Skillset",
      "Culture of innovation",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Merdice Evans",
    "potentialRisksOrRoadblocks": "-",
    "expense": 2000000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "Customer Experience Engineering (CxE)",
    "projectId": "JSC-0048345",
    "startDate": "2/7/22",
    "primary": "Patient & Consumer Q",
    "totalProjectCost": 2000000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Karen O'Hagan,C. Elizabeth Truman",
    "affectedQCDimensions": "",
    "capital": 872000,
    "functionalOwnership": "Pharm - Business Quality",
    "involvedTechnologyOrSystem": "PQMS",
    "totalProjectValue": 200000,
    "endDate": "12/1/24",
    "description": "PQMS automation and data integration improvements.  A stable team will be kept in place to address system enhancements, incidents, and Business Partner releases between the platform. This record/CAR is for the Pharm portion of the stable team splitting with Consumer.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "Maintain a Stable team in support of PQMS for product quality complaints to ensure Compliance to Global Regulatory Requirements, sustain system maintenance, deliver business needs and drive digital roadmap automation.",
    "resourceRequired": "TBD",
    "initiative": "Complaints Compliance and Improvement",
    "carStatus": "",
    "strategies": [
      "Culture of innovation",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Sharon Luzie",
    "potentialRisksOrRoadblocks": "-",
    "expense": 353000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "BP22 - Complaints Compliance and Improvements - STABLE TEAMS PQMS",
    "projectId": "JSC-0045397",
    "startDate": "2/14/22",
    "primary": "Patient & Consumer Q",
    "totalProjectCost": 1225000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "CDL",
    "totalProjectValue": 0,
    "endDate": "9/15/24",
    "description": "Continued funding for CDL ingestion work",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Ingestion of following data sources:\n- eLIMS\n- Empower\n- SmartQC\n- SmartQA",
    "resourceRequired": "TBD",
    "initiative": "-",
    "carStatus": "",
    "strategies": [
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 500000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "Quality CDL Data Ingestion",
    "projectId": "JSC-0046962",
    "startDate": "1/1/22",
    "primary": "Data & Analytics",
    "totalProjectCost": 500000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Carmen Verhoeven",
    "affectedQCDimensions": "",
    "capital": 1579251,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Paperless Labs",
    "totalProjectValue": 800000,
    "endDate": "5/26/27",
    "description": "Deployment of Paperless Labs in the labs: enhancement of the LME functionality in Elims, instrument connections, implementation of paperless methods replacing worksheets or logbooks)",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "LOTF: Deployment of Paperless Labs according to the roadmap in JSC One Lab organization.\nIncluding:\n- Instrument connections\n- Implementation of paperless methods replacing worksheets or other paper-based methods\n- Harmonization of methods across the network (whenever possible)\n- Implementation of reagent module",
    "resourceRequired": "TBD",
    "initiative": "Paperless Labs 2022",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 638661,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "QC OPERATIONS BP22 - Paperless labs",
    "projectId": "JSC-0045415",
    "startDate": "3/31/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 2217912
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 370000,
    "endDate": "9/30/25",
    "description": "Implementation of projects enhancing lab operation by introducing automation.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "New Technology Roadmap for automation in JSC CQ Labs:\n1) To deploy DNA qPCR to remove radioactive probe for testing IPC samples in Cork Bio and Leiden\n2) To deploy Growth Direct to test Enviromental Monitoring samples in Cork and Schaffausen\n3) Labotica: To implement a pilot technology in Latina to fully automate tablets weight, NIRtesting, sample preparation and evaluate the scalability\n4) TECAN: The purpose of this project is to implement the valiadated, automated  methods to Leiden, Schaffhausen and Cork labs.",
    "resourceRequired": "TBD",
    "initiative": "Automation of QC Lab Operations",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 223307,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP21 - AC CoE - Automation of QC Lab Operations",
    "projectId": "JSC-0099588",
    "startDate": "1/1/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 223307
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "David Enck",
    "affectedQCDimensions": "",
    "capital": 723500,
    "functionalOwnership": "Pharm - Product Quality Mgmt",
    "involvedTechnologyOrSystem": "PQM Work Center",
    "totalProjectValue": 0,
    "endDate": "5/5/24",
    "description": "A solution that will increase the efficiency and capability to assure Product Quality given the documents, reports, and records that PQOs have to manage from TOO to product delisting/divesting.",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "PQM Work Center aims to improve the efficiency of accessing product related data from multiple source systems to support products that are in commercial production. The product data currently accessed by PQM professionals come from a variety of data sources such as:\n- Trackwise (Quality data such as Complaints, CAPA, NC’s, CR’s etc.), \n- RIM Docs and TruVault,\n- Laboratory Information Management System (LIMS),\n- SAP.\nThe goal of this project is to aggregate product related information from these systems via the Common Data Layer (CDL) and allow PQM professionals to persist links between data for specific products from these disparate data sources and create Product Specific Dashboards. \n",
    "resourceRequired": "TBD",
    "initiative": "PQM Work Center",
    "carStatus": "",
    "strategies": [
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Juergen Wolfgang",
    "potentialRisksOrRoadblocks": "Timing of the Common Data Layer connection as specified by JJT is the biggest project efficiency/timing risk.\nPQM Work Center can use the CDL as currently configured, the continuing work by JJT on the CDL will simplify the work for PQM Work Center\nProject can leverage work by Next Gen QS, however PQM Work Center can proceed even if Next Gen QS project is delayed.",
    "expense": 262000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "PQM Work-Center 2022 (PQO)",
    "projectId": "JSC-0045663",
    "startDate": "12/10/21",
    "primary": "Data & Analytics",
    "totalProjectCost": 985500
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 1475000,
    "endDate": "9/15/24",
    "description": "Quality BOTs, cognitive automation and digitalization.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "- Quality Bots for transactional and rule-based repetitive Quality tasks including remote work, Quality Oversight and full automation of Digital Batch Release, moving from IT-guided to self service\n- Cognitive automation for complex and human-logic Quality activities including e2e processing of Quality tasks and processes in release and oversight\n- Automation and digitalization of system and process adoption",
    "resourceRequired": "TBD",
    "initiative": "Intelligent Automaton in Quality",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 510000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - Intelligent Automation in Quality",
    "projectId": "JSC-0046000",
    "startDate": "1/1/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 510000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Carmen Verhoeven",
    "affectedQCDimensions": "",
    "capital": 486755.9100000001,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Paperless Labs",
    "totalProjectValue": 650000,
    "endDate": "5/26/24",
    "description": "Deployment of Paperless Labs in the labs: enhancement of the LME functionality in Elims, instrument connections, implementation of paperless methods replacing worksheets or logbooks)",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "LOTF: Deployment of Paperless Labs according to the roadmap in JSC One Lab organization.\nIncluding:\n- Instrument connections\n- Implementation of paperless methods replacing worksheets or other paper-based methods\n- Harmonization of methods across the network (whenever possible)\n- Implementation of reagent module",
    "resourceRequired": "TBD",
    "initiative": "Paperless Labs 2021",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "lack of IT resources",
    "expense": 789846.0574,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "Lab Systems - Paperless Labs - 2021",
    "projectId": "JSC-0099848",
    "startDate": "5/31/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 1276601.9674000002
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Sarah Nielsen",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Quality Assurance",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 1550000,
    "endDate": "9/15/24",
    "description": "Funding for the small molecule digital integrated quality roadmap. ",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "The funds will:\n1.\t~200k: Finalize the Geel Apalutamide DP Intermediate Project (expected savings ~3MM over 10 years)\n2.\t~100k: Development of models for Zyrtec, Benadryl and Simply Sleep (for our Latina and Gurabo Sites) and 2 Pharma products (DPDS back charge) – Business Value -  all these products will be less than 1 day release\n3.\t~210k: Erleada DP Real Time Release including Incoming Raw Material PAT testing (business case TBS, but expected to be on the order of 1.5MM over 10 years)\n4.\t~220k: Daruavir End to End RTR (Fund a DOE to control particle size of Darunavir for Symtuza, Business case on the order of 1.0MM SLOB reduction)\n5.\t~50k: Business support lead backcharge.  Charge out for headcount to support project implementation.\n",
    "resourceRequired": "TBD",
    "initiative": "Integrated Quality",
    "carStatus": "",
    "strategies": [
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 774000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "2022_Integrated Quality",
    "projectId": "JSC-0056633",
    "startDate": "1/1/22",
    "primary": "Data & Analytics",
    "totalProjectCost": 774000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "10/31/23",
    "description": "Remediation of method perfromance issues (SM and LM) as determined and prioritized from the Lab Compliance Initiative Methods Workstream, LCI MT2 primary deliverable.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "As per defined and approved action plans (as per QS records) remediate method perfromance issues (SM and LM) as determined and prioritized from the Lab Compliance Initiative Methods Workstream, LCI MT2 primary deliverable. Implement corrective actions.\nMultiple site are involved.",
    "resourceRequired": "TBD",
    "initiative": "LCI Methods Remediation",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Patient & Consumer Q"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 99900.5,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Compliance",
    "projectName": "BP22 - AC CoE -JSCQ Lab Compliance Initiative_Methods remediation (SM_LM)",
    "projectId": "JSC-0045634",
    "startDate": "2/17/21",
    "primary": "Patient & Consumer Q",
    "totalProjectCost": 99900.5
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 630000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "eLIMS",
    "totalProjectValue": 0,
    "endDate": "12/1/24",
    "description": "eLIMS - Continuous improvement eLIMS system, reports, and trending tools to improve compliance, DI, productivity and efficiency in all labs.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "Business Objectives/Expectations: Will be finalised Q4, 2021 (For 2021, extended external roles to enable ECL & EM integration to support vaccines, enhanced RTR functionality, controlled substance functionality to sync with local health authority commitments, include new regulatory requirements for Certificate of Analysis (CofA), iLABs functionality to enable paperless labs and related audit trail reports, automate stability management and government. eLIMS will be upgraded to version LV 8.6 to align Oracle version of database.",
    "resourceRequired": "TBD",
    "initiative": "eLIMS",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 425000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "QC OPERATIONS BP22 - eLIMS.",
    "projectId": "JSC-0057874",
    "startDate": "1//2022",
    "primary": "Intelligent Automation",
    "totalProjectCost": 1055000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 187304,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 1960000,
    "endDate": "9/15/24",
    "description": "Create insights into the performance of Quality across sites by standardizing reports and metrics. Reports will be auto-generated to enable dedication of more time to value added work.",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "- Descriptive and diagnostic Quality and Business Performance analytics (information, data, metrics). Data Analytics exploration and R&D\n- Auto-generation of Periodic Review Reports \n- Proactive compliance and risk monitor on external Quality (Supplier risk monitoring, Material risk monitoring, processes, product, operations, etc)\n- Proactive compliance and risk monitor on internal processes, product, operations, etc \n- GMPification of the Data Science Applications and Solutions\n",
    "resourceRequired": "TBD",
    "initiative": "Quantify the State of Quality",
    "carStatus": "",
    "strategies": [
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 125000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - QuantifytheStateofQuality",
    "projectId": "JSC-0046001",
    "startDate": "1/1/22",
    "primary": "Data & Analytics",
    "totalProjectCost": 312304
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 460000,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 1608000,
    "endDate": "12/24/23",
    "description": "Deployment and sustainability of advanced analytics solution across the Large Molecule Platform (Leiden, Schaffhausen, Cork and Malvern).",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Driving business value through data analytics and democratized data through increase in manufacturing yield, product throughput, reliability and reduction in Cost of poor Quality is a strategic imperative. After successfully proving the business value in initial deployments, the Prometheus project and the NC Advanced Analytics project will integrate to form Supply Chain Analytics (SCAN) and start scaling the pressure tested digital toolbox across JSC Make with focus on the Large Molecule Platform (Cork, Leiden, and Schaffhausen). Through the established and tested SCAN-Process, deployment and expansion of the advanced analytical solutions will focus on the Large Molecule Platform.",
    "resourceRequired": "TBD",
    "initiative": "SCAN (Scale LM Platform)",
    "carStatus": "",
    "strategies": [
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "1) Interdependent projects do not deliver the data foundation needed (CDL (Common Data Layer), MDH (Manufacturing Data Hub)) to fully scale in 2021.\nMitigation: Monitoring of established data pipelines by SCAN team to assure seamless integration. Current existing data access and architecture will be maintained until MDH readiness is achieved. \n2) Key resources with the critical skill set in modeling, data engineering and business know how are not available to the project.\nMitigation: Definition of key resources to be committed to project are defined and committed by the different functions.",
    "expense": 230000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "SCAN  (Scale LM Platform) - Janssen Genius",
    "projectId": "JSC-0102217",
    "startDate": "9/25/20",
    "primary": "Intelligent Automation",
    "totalProjectCost": 690000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 250000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "6/30/24",
    "description": "Collaboration Project PCM-Quality to integrate and create flow.",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Improve supply chain integration, create transparency in current and future lab capacity within the network and across the Sectors, standardize planning processes across the labs.",
    "resourceRequired": "TBD",
    "initiative": "Clarity Project Partnership PCM-Quality",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 250000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "QC OPERATIONS BP22-CLARITY Project-Partnership PCM-Quality",
    "projectId": "JSC-0045426",
    "startDate": "6/30/22",
    "primary": "Patient & Consumer Q",
    "totalProjectCost": 500000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Loic Hascher",
    "affectedQCDimensions": "",
    "capital": 519684,
    "functionalOwnership": "Pharm - Quality Systems",
    "involvedTechnologyOrSystem": "APQR",
    "totalProjectValue": 333000,
    "endDate": "11/30/23",
    "description": "Development of an end to end Annual Product Review facilitated by automation, via creation of standardized Tableau queries, upgrade of the APQR Schedule Tool and development of a Schedule Predictor Tool. ",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Development of an end to end Annual Product Review facilitated by automation, via creation of standardized Tableau queries, upgrade of the APQR Schedule Tool and development of a Schedule Predictor Tool are the deliverables of the project.",
    "resourceRequired": "TBD",
    "initiative": "APQR",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Rob Famiglietti",
    "potentialRisksOrRoadblocks": "-",
    "expense": 106902,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Compliance",
    "projectName": "BP21 - APQR (IT_1135509)",
    "projectId": "JSC-0042099",
    "startDate": "6/30/21",
    "primary": "Internal Quality Support",
    "totalProjectCost": 626586
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 25000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "SDMS",
    "totalProjectValue": 0,
    "endDate": "10/29/24",
    "description": "Janssen Supply Chain Quality Labs Funding for Licenses, Connections and IT SOWs for SDMS. ",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "The SDMS Application is the mandated IT Platform & Solution for the Back Up & Restore of all GXP Lab Analytical Instrument Electronic Data. It is a foundational elements in the Data Integrity Compliance in our Labs.",
    "resourceRequired": "TBD",
    "initiative": "SDMS",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 156000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "BP22 JSCQ QC Operation SDMS Pharma Sector",
    "projectId": "JSC-0045696",
    "startDate": "12/1/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 181000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Empower",
    "totalProjectValue": 0,
    "endDate": "12/1/24",
    "description": "Empower: New Instrument drivers / DAC upgrade / config changes, Data Analytics.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "New Instrument drivers / DAC upgrade / config changes, Data Analytics.",
    "resourceRequired": "TBD",
    "initiative": "Empower",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 370000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "QC OPERATIONS BP22 - Empower.",
    "projectId": "JSC-0057886",
    "startDate": "1/1/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 370000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 510000,
    "endDate": "9/15/24",
    "description": "Realize exception-based batch review and release through automating and optimizing batch review and release processes driven by elimination of most transactional activities.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "Realize exception-based batch review and release through automating and optimizing batch review and release processes driven by elimination of most transactional activities.",
    "resourceRequired": "TBD",
    "initiative": "Digital Product Release",
    "carStatus": "",
    "strategies": [
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 175000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - Digital Product Release",
    "projectId": "JSC-0046005",
    "startDate": "1/1/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 175000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "9/15/24",
    "description": "Build internal capability to create and deploy technology, digital and automation solutions, and to evolve from descriptive analytics to advanced analytics.",
    "roi": "",
    "bamAllignment": "75% Focused on Patient, Consumer & Customer Exp",
    "businessObjectivesOrExpectations": "- Data: Tableau training and Tableau CoP events and developer support (includes refresher and expansion training sessions)\n- Data: Azure Databricks for people with coding skills, and Azure Databricks for people with Tableau skills (includes refresher and expansion training sessions)\n- Data Science Boot Camp Participants: 6 month assignment in COE including Data science bootcamp externally\n- Capability build for novel requirements (ML, data architecture, …)",
    "resourceRequired": "TBD",
    "initiative": "Quality DNA ",
    "carStatus": "",
    "strategies": [
      "Skillset",
      "Culture of innovation",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 290000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - Technology and Data Savviness in Quality DNA",
    "projectId": "JSC-0046003",
    "startDate": "1/1/22",
    "primary": "Skillset",
    "totalProjectCost": 290000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Koen Mol",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Business Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 148000,
    "endDate": "1/31/24",
    "description": "Part of AcceleRRAte BQ project group.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "Enhancements to JC Qualize are aimed at allowing other functions at LOC level to manage the gap assessment and training management in a similar automated fashion as was developed for CQ. This enhancement mainly impacts Regulatory Affairs. Completion and implementation is expected in Q2 2022. A total investment of $300K is requested.",
    "resourceRequired": "TBD",
    "initiative": "BQ QM JC Quality Enhancements",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support"
    ],
    "projectSponsor": "Sharon Luzie",
    "potentialRisksOrRoadblocks": "-",
    "expense": 650000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BQ QM JC Qualize enhancements",
    "projectId": "JSC-0047591",
    "startDate": "3/4/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 650000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 5000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Compliance Builder",
    "totalProjectValue": 0,
    "endDate": "10/29/24",
    "description": "Janssen Supply Chain Quality Labs Funding for Licenses, Connections and IT SOWs for Compliance Builder.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "To address Data Integrity Gaps on Lab Analytical Instruments that cannot be remediated through instrument replacement, or Firm/Software upgrade. Compliance Builder is the mandated IT Platform & Solution to resolve the following issue: Internal Security-Access Limitations/Audit Train/Data & Time Controls, Data Management, Date Retrieval.",
    "resourceRequired": "TBD",
    "initiative": "Compliance Builder",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 20000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "BP22 JSCQ QC Operation Compliance Builder Pharma Sector",
    "projectId": "JSC-0045688",
    "startDate": "1/1/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 25000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 114000,
    "endDate": "12/31/25",
    "description": "Reduction of Time to Release (TTR) and automation of read-out of EM plates.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "The purpose of this project is to expand the scope of applications and  deploy for Grade A samples (Beerse and Schaffhausen) and for batch related samples (EM-IPC) in Cork and Leiden. A new process for sampling and documentation, as well as a new interface between SAP ERP2 and eLIMS needs to be created. (Schaffhausen, Beerse)",
    "resourceRequired": "TBD",
    "initiative": "Automation - Environmental Monitoring",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 99547.91,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - AC CoE - Automated read-out of plates taken for environmental monitoring.",
    "projectId": "JSC-0045620",
    "startDate": "2/17/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 99547.91
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Isabel Verbruggen",
    "affectedQCDimensions": "",
    "capital": 100000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 300000,
    "endDate": "8/22/24",
    "description": "External Lab integration (integration of external labs with J&J Lab Systems - Interface building with external systems).",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "- Paperless integration external labs (error proofing), eg  COVID supply chain and CAR-T/Legend partnership  \n     -  IT integration of external labs with J&J Lab Systems, LIMS & Smart QC \n- Reduction of time  \n- Avoiding Human error with transcribing data\n- COVID-19  Support - External Lab and External Manufactures\n- CAR-T / Legend partnership\n- Interface building with external system",
    "resourceRequired": "TBD",
    "initiative": "External Lab Integration",
    "carStatus": "",
    "strategies": [
      "Partner Ecosystem"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 350000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "QC OPERATIONS BP22 - External Lab integration",
    "projectId": "JSC-0045418",
    "startDate": "4/30/22",
    "primary": "Partner Ecosystem",
    "totalProjectCost": 450000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Katelyn Walsh",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Quality PPM",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "5/23/24",
    "description": "Janssen Controlled Substance Metrics.",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "In 2020, develop a URS for Controlled Substance E2E data and metrics for IT system and dashboard requirements\nIn 2021, implement the E2E metrics system (update existing systems and create required dashboards)\n2022 TBD",
    "resourceRequired": "TBD",
    "initiative": "Controlled Substance Metrics",
    "carStatus": "",
    "strategies": [
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Joseph Shepard",
    "potentialRisksOrRoadblocks": "Difficulty in identification of records that are related to CS; this could be due to inconsistency in data entry and lack of consistent product master data information.  This project will only focus on existing data and will not address data entry processes.",
    "expense": 350000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "Janssen Controlled Substance Metrics",
    "projectId": "JSC-0034352",
    "startDate": "1/1/21",
    "primary": "Data & Analytics",
    "totalProjectCost": 350000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Koen Mol",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Business Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 30000,
    "endDate": "1/31/24",
    "description": "BQ AcceleRRAte project.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "Enhancements to the Data Warehouse to ensure the AcceleRRAte team has full visibility on parameters that allow to identify risks for non-compliance with Patient Support Programs. This impacts the global oversight as well as visibility for the local operating company RRA oversight committees. A total investment of $ 150k is requested in 2022.",
    "resourceRequired": "TBD",
    "initiative": "-",
    "carStatus": "",
    "strategies": [
      "Culture of innovation",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Sharon Luzie",
    "potentialRisksOrRoadblocks": "-",
    "expense": 150000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "AcceleRRAte Risk Insights",
    "projectId": "JSC-0047590",
    "startDate": "3/4/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 150000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Carmen Verhoeven",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Smart QA",
    "totalProjectValue": 10000000,
    "endDate": "1/14/25",
    "description": "Implementation of Smart QA at Fuji, Xian, Korea, Brazil, Mexico, Athens, Actelion. Further system enhancements to enable QA performance mgt.",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Implementation of Smart QA\nFuji, Xian, Korea, Brazil, Mexico, Athens, Actelion\n\nFurther system enhancements to enable QA performance mgt",
    "resourceRequired": "TBD",
    "initiative": "SMART QA 2021",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "Lack of IT resources.",
    "expense": 224000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "Lab Systems - Smart QA - 2021",
    "projectId": "JSC-0099829",
    "startDate": "9/30/21",
    "primary": "Intelligent Automation",
    "totalProjectCost": 224000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Koen Mol",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Business Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 160000,
    "endDate": "1/30/24",
    "description": "BQ AcceleRRAte project.",
    "roi": "",
    "bamAllignment": "N/A",
    "businessObjectivesOrExpectations": "RRAMS Release 2 is aimed at adding functionality to RRAMS to further integrate the RRA process in the system: link with the concept approval, new way of working for the reconciliation process, add the non-compliance processes and allow the users to view the audit trail. This impacts both the Pharma Commercial groups and the Central PV HUB. Completion and implementation is expected in Q3 2022. An investment of $ 350 k is requested for this release in 2022.",
    "resourceRequired": "TBD",
    "initiative": "-",
    "carStatus": "",
    "strategies": [
      "Culture of innovation",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Sharon Luzie",
    "potentialRisksOrRoadblocks": "-",
    "expense": 427000.001,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "AcceleRRAte RRAMS enhancement",
    "projectId": "JSC-0047464",
    "startDate": "3/3/21",
    "primary": "Data & Analytics",
    "totalProjectCost": 427000.001
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Isabel Verbruggen",
    "affectedQCDimensions": "",
    "capital": 75000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 50000,
    "endDate": "1/21/25",
    "description": "Innovation and technologies (enhance and automate the end user experience with eLims/iLABs).",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "This project is a compilation of innovation initiatives that will further enhance and automate the end user experience with eLims/iLABs and automate the masterdata setup in the system. Today masterdata setup and maintenance is a very manual and labour intense process. The requested budget will be used to support CPI, Test & learns / Proof of concept testing and implementations of 2021 T&L ideas. \nEnd user experience elims, efficiency, iLAB enabling\nHands free login: Provide a more efficient way to login with an Iris or fingerprint scan.\nImprove sample Track&Trace: A digital sample ‘Track & Trace’ system using RFID technology\nVoice recognition: Reduce look-up activities by providing instructions in technician's line of sight (visual/auditory cues), Facilitate Data Entry by using voice\nad hoc sample log: Automate Manual log in of samples for non standard samples (e.g. NPI, cleaning) ( 0,2 FTE/site)\nMaster data automation elims: \nMaster data Comparison: Have a tool available that can automatically highlight all changes both for specification in TV and eLIMS\nTest selection: Cognition Cockpit improvement: it will allow to do reporting and trending without manipulation of the data\nDynamic Forms: Have an electronic smart input FORM for master data request available",
    "resourceRequired": "TBD",
    "initiative": "QC Ops Innovation and Technologies",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 200000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "QC OPERATIONS BP22 - Innovation and technologies",
    "projectId": "JSC-0045417",
    "startDate": "5/11/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 275000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 100000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "12/1/24",
    "description": "RTR (deployment new techniques).",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "SynTQ is a system that is implemented in 2020 as a pilot project in Gurabo for CANA NIR content uniformity test execution.  The systems is needed to support in the management of the spectral models and calculations (which was a manual process before).  Next steps will be to further deploy SynTQ for managing NIR E2E processes in Geel, Latina and Gurabo:  Test Execution, Model Verification, Model Transfer, Track and Trend fully integrated with eLIMs and the Bruker software.",
    "resourceRequired": "TBD",
    "initiative": "RTR",
    "carStatus": "",
    "strategies": [
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 200000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "QC OPERATIONS BP22 - RTR.",
    "projectId": "JSC-0057879",
    "startDate": "1/1/22",
    "primary": "Data & Analytics",
    "totalProjectCost": 300000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Isabel Verbruggen",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 150000,
    "endDate": "1/8/24",
    "description": "Pharma Data Portal BP2022 (keep the lights on).",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Business Objectives/Expectations: Keep the lights on untill Next Gen QS roadmap and scope is clear",
    "resourceRequired": "TBD",
    "initiative": "Pharma Data Portal",
    "carStatus": "",
    "strategies": [
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 150000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "QC OPERATIONS BP22 - Pharma Data Portal",
    "projectId": "JSC-0045027",
    "startDate": "2/28/22",
    "primary": "Data & Analytics",
    "totalProjectCost": 150000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 77000,
    "endDate": "12/1/24",
    "description": "Replacement of current technology to move to a no-radioactive technology for Simponi and Remicade.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "The objective of this project is to replace the current, radioactive based testing for SImponi and Remicade with a new method that provides significant EH&S benefits. \nInvolved sites are Cork, Leiden.",
    "resourceRequired": "TBD",
    "initiative": "JSCQ Lab Rapid Methods",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 150000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "BP22 - AC CoE - JSCQ lab rapid  methods (DNA qPCR) implementation (BT)",
    "projectId": "JSC-0057864",
    "startDate": "1/1/22",
    "primary": "Internal Quality Support",
    "totalProjectCost": 150000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 5274210,
    "endDate": "12/31/25",
    "description": "Reduction of Cycle Time by fully automated Mycoplasma Testing (BioFire). Pilot site will be Leiden.",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "Deployment of this automated and rapid technology for Mycoplasma Testing in Leiden for selected products.",
    "resourceRequired": "TBD",
    "initiative": "Automated Mycoplasma Test (BioFire)",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 47012,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - AC CoE - Automated and rapid Mycoplasma Test (BioFire)",
    "projectId": "JSC-0045592",
    "startDate": "2/17/21",
    "primary": "Operational Efficiencies",
    "totalProjectCost": 47012
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Loic Hascher",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Quality Systems",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 0,
    "endDate": "9/15/24",
    "description": "This investment will cover development of wearables roadmap for Quality Systems, and fund development and delivery of solutions.  In addition, a portion of this funding will cover the central costs of initial procurement of devices for deployment",
    "roi": "",
    "bamAllignment": "100% Digital QMS",
    "businessObjectivesOrExpectations": "This investment will cover development of wearables roadmap for Quality Systems, and fund development and delivery of solutions.  In addition, a portion of this funding will cover the central costs of initial procurement of devices for deployment within Q&C.  The primary focus of this effort will be to deploy \"See what I see\" technology to groups across Janssen Q&C.  This will include capabilities for performing virtual remote audits, virtual method transfer, employee training, complaint sample inspection, and other targets, as defined by the Janssen Wearables Council.  This funding will also cover exploratory work into augmented and virtual reality applications for Quality Systems.  Total cost per device with GTS central support currently at $9400.00.  Ten pairs * 23 sites * $6000 per device = $1.4MM.  Will assume over two years, as technology will evolve rapidly.  Including additional $ (double) for development and validation costs",
    "resourceRequired": "TBD",
    "initiative": "Wearables",
    "carStatus": "",
    "strategies": [
      "Culture of innovation",
      "Partner Ecosystem",
      "Operational Efficiencies",
      "Internal Quality Support"
    ],
    "projectSponsor": "Rob Famiglietti",
    "potentialRisksOrRoadblocks": "-",
    "expense": 40000,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - Wearables",
    "projectId": "JSC-0045223",
    "startDate": "1/3/22",
    "primary": "Culture of innovation",
    "totalProjectCost": 40000
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 29382.5,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TruTools",
    "totalProjectValue": 0,
    "endDate": "10/26/25",
    "description": "Implementation of Trutools, an improved software application linked to the Raman spectroscopy based rapid identification methods. ",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "Implementation of Trutools, an improved software application linked to the Raman spectroscopy based rapid identification methods.\nSite in scope are Latina, Beerse, Geel, Cork, Schaffausen, Gurabo, Mexico, Brazil, Xian.\nThis application improves the specificity of the method thereby expanding the applicability to more products.",
    "resourceRequired": "TBD",
    "initiative": "JSCQ Tru Tools Implementation",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 0,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Base",
    "projectName": "BP22 - AC CoE - JSCQ lab TruTools Software implementation (SM)",
    "projectId": "JSC-0045286",
    "startDate": "1/1/22",
    "primary": "Internal Quality Support",
    "totalProjectCost": 29382.5
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Peggy Van Herzeele,Bill Fouhy,Carmen Verhoeven",
    "affectedQCDimensions": "",
    "capital": 50000,
    "functionalOwnership": "JSCQ - Lab Systems",
    "involvedTechnologyOrSystem": "Smart QA",
    "totalProjectValue": 300000,
    "endDate": "12/31/25",
    "description": "Smart QA (further deployments)",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Implementation of Smart QA at more sites\n-\t3 sites: Puebla (B2B); Manati (Sustain), Incheon (PANDA)\n- B2B = leverage from Brazil SJC\n- Sustain = leverage from 2020 sites\n- Panda = leverage from 2021\n- Interface TW on CDL\n\n- Smart QA is a SaaS solution implemented across several Janssen sites. It  increases the visibility and efficiency of the batch release process and enables reduction of variability in batch release cycle times, allowing inventory reduction.  It provides full visibility on batch release interdependencies and batch record review execution.  Smart QA is streamlined with release against agreed standards and priority management.  It is cross-functional with alignment across functions to drive down variation and cycle time.  It has fully automated interfaces to bring information into one place.  There is standardized metrics across sites.  Planning performance is improved by close collaboration.",
    "resourceRequired": "TBD",
    "initiative": "SMART QA 2022",
    "carStatus": "",
    "strategies": [
      "Intelligent Automation"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 81999,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "QC OPERATIONS BP22 - Smart QA",
    "projectId": "JSC-0045427",
    "startDate": "4/28/22",
    "primary": "Intelligent Automation",
    "totalProjectCost": 131999
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Marzia Grassi,Bill Fouhy",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "JSCQ - CoE Lab Operations",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 38000,
    "endDate": "11/2/25",
    "description": "Halogen Moisture Analyzer (HMA) replacing the traditional loss on drying (LOD) testing on raw material (SM). ",
    "roi": "",
    "bamAllignment": "80% Automated QC and Product Release",
    "businessObjectivesOrExpectations": "The purpose of this project is to implement rapid moisture analysis to replace traditional loss-on-drying test (LOD) in a JSCQ Lab that will be determined in 2021.",
    "resourceRequired": "TBD",
    "initiative": "JSQC Lab Rapid Technology Implementation (HMA)",
    "carStatus": "",
    "strategies": [
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 51713.2,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP22 - AC CoE - JSCQ lab rapid  technology  (HMA) implementation (SM)",
    "projectId": "JSC-0045579",
    "startDate": "2/17/21",
    "primary": "Operational Efficiencies",
    "totalProjectCost": 51713.2
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Christian Dubs",
    "affectedQCDimensions": "",
    "capital": 422000,
    "functionalOwnership": "JSCQ - Transformational Quality",
    "involvedTechnologyOrSystem": "TBD",
    "totalProjectValue": 2145000,
    "endDate": "9/14/23",
    "description": "Create insights into the performance of Quality across sites by standardizing reports and metrics. Reports will be auto generated to enable us to dedicate more time to value adding work.  ",
    "roi": "",
    "bamAllignment": "100% Integrated Data",
    "businessObjectivesOrExpectations": "Increase information availability real-time  Improve data driven decision making  Improve reliability/reduce human errors  Harmonize/standardize dashboards and metrics across sites  Reduce time required to prepare reports with a potential to increase efficiency",
    "resourceRequired": "TBD",
    "initiative": "JSCQ Transformational Quality",
    "carStatus": "",
    "strategies": [
      "Internal Quality Support",
      "Data & Analytics"
    ],
    "projectSponsor": "Swroop Sahota",
    "potentialRisksOrRoadblocks": "-",
    "expense": 40696,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "BP21 - JSCQ Transformational Quality - _QuantifytheStateofQuality",
    "projectId": "JSC-0099481",
    "startDate": "6/30/21",
    "primary": "Data & Analytics",
    "totalProjectCost": 462696
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Loic Hascher,Sue Gifaldi",
    "affectedQCDimensions": "",
    "capital": 0,
    "functionalOwnership": "Pharm - Quality Systems",
    "involvedTechnologyOrSystem": "Jaccard",
    "totalProjectValue": "N/A",
    "endDate": "1/17/22",
    "description": "Mahjong is an AI based tool that allows a Trackwise QEM user to compare a single non-conformance to previous ones and find similarities based on Natural Language Processing (NLP) algorithms. ",
    "roi": "",
    "bamAllignment": "100% Digital QMS",
    "businessObjectivesOrExpectations": "Mahjong for Pharma is a fully validated, advanced analytics tool, available to all TrackWise QEM users, that allows a user to compare a single quality investigation to previous quality investigations and find similarities based on Natural Language Processing (NLP) algorithms. \n\nWith NLP, Mahjong can detect language patterns and identify similarities inside complex and numerous records. ",
    "resourceRequired": "TBD",
    "initiative": "Mahjong",
    "carStatus": "",
    "strategies": [
      "Culture of innovation",
      "Operational Efficiencies",
      "Internal Quality Support",
      "Data & Analytics",
      "Intelligent Automation"
    ],
    "projectSponsor": "Rob Famiglietti",
    "potentialRisksOrRoadblocks": "",
    "expense": 524615,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Compliance",
    "projectName": "N/A",
    "projectId": "N/A",
    "startDate": "9/1/21",
    "primary": "Internal Quality Support",
    "totalProjectCost": 524615
  },
  {
    "rpaValueScore": "TBD",
    "projectManager": "Rafe Tan",
    "affectedQCDimensions": "",
    "capital": 646153,
    "functionalOwnership": "Pharm - Commercial Quality",
    "involvedTechnologyOrSystem": "AI, NLP, KunPeng, Trackwise, RIACS, Insight,  Arctic, SAP, etc.",
    "totalProjectValue": "TBD",
    "endDate": "12/31/24",
    "description": "To improve Janssen China LOC quality and regulatory compliance while strengthening our operations, driving incremental improvement, enabling business growth and transforming into future readiness through below 5 key projects:\n1. Improve future China NRDL product supply reliability through digital solutions, process and strategy streamlining to free up more workload in the future.\n2. Set up process and automatic system for Annual Report to comply with regulatory requirement and drive efficiency and accuracy.\n3. Initiate MAH datahub to support MAH responsibilities and related regulation deployment\n4. Establish the new process/approach to support AE/PQC reporting and identification through new IT technical solution(AI) launch in XJP LOC and comply with China regulations.\n5. Optimize E2E CMC change process, prepare for organizational readiness and system integration to ensure post approval CMC changes be accurately assessed according to China regulatory requirement.",
    "roi": "",
    "bamAllignment": "75% of our time is proactively focused on the patient, consumer, and Cx\n",
    "businessObjectivesOrExpectations": "China Advancement Plan will improve Janssen China LOC overall quality and regulatory compliance level and bring benefit to business growth through 5 key projects objectives realized: \n1. Improve China NRDL product supply reliability, realize 3X growth financial target, free up more workload in the future.\n2. Process and automatic system of Annual Report will help to comply with regulatory requirement and drive efficiency and accuracy, and reduce manual work and rounds of communication and clarification.\n3. MAH datahub digital tool will reduce manual work and improve efficiency.\n4. New quality digital operating model and high efficiency approach will provide patient-centric solutions to realize Janssen China business 3X growth. LOC quality compliance database will advance the use of data science and analytics across Janssen China to accelerate quality insights.\n5. Optimized E2E CMC change process, organization and system will ensure compliance and reduce manual work.",
    "resourceRequired": "Contractor - 2",
    "initiative": "China Advancement Plan 3.0",
    "carStatus": "",
    "strategies": [
      "Internal Quality Support",
      "Patient & Consumer Q",
      "Data & Analytics"
    ],
    "projectSponsor": "Yan Qunmei, Ricco.E, Upendra.K, Zhang Lei (Layla), Theerayoot.A, Yu Lihui",
    "potentialRisksOrRoadblocks": "External evolving regulatory environment uncertainty and lack of clarity from HA intepretation of the regulations.\nDifficulties in synergizing with evolving global system and interfacing with global systems such as RIACS, Trackwise, Insight, etc.",
    "expense": 307693,
    "janssenOneAccelerator": "Show graphic, no linkage",
    "qualityEnabler": "Default to Accelerators",
    "investmentType": "Strategic",
    "projectName": "N/A",
    "projectId": "N/A",
    "startDate": "1/1/22",
    "primary": "Patient & Consumer Q",
    "totalProjectCost": 953846
  }
];

const bamAlignments = [
    {
        "name": "100% Digital QMS",
        "fill": "#de4c4f"
    },
    {
        "name": "98% Satisfaction in Customer Facing KPIs",
        "fill": "#eea638"
    },
    {
        "name": "80% Automated QC and Product Release",
        "fill": "#86a965"
    },
    {
        "name": "100% Integrated Data",
        "fill": "#a7a737"
    },
    {
        "name": "75% Focused on Patient, Consumer & Customer Exp",
        "fill": "#d8854f"
    },
    {
        "name": "N/A",
        "fill": "#3399FF"
    }
];

const getBAMAlignments = (rawData: any) => {
    let result: any = [];
    var nf = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
    });
    bamAlignments.forEach(element => {
        let initiatives = rawData.filter(item => item.bamAllignment == element.name);
        let totalProjectsCost = initiatives.reduce(function (acc, obj) { return acc + (obj.totalProjectCost ? obj.totalProjectCost : 0) }, 0);
        result.push({ "name": element.name, "fill": element.fill, "value": 1, "initiatives": initiatives.length, "totalProjectsCost": nf.format(totalProjectsCost) });

    });
    return result;
};

export { chart2data, getBAMAlignments, bamAlignments };
